# Sports Tweet

In [1]:
#pip install snscrape 
#Sports

In [2]:
import pandas as pd
import snscrape.modules.twitter as sn

In [3]:
em=sn.TwitterUserScraper("FIFAcom")

In [4]:
li=[]
for i,tweet in enumerate(em.get_items()):
    if i>100:
        break
    li.append([tweet.rawContent,tweet.date,tweet.likeCount,tweet.retweetCount,tweet.replyCount,"Sports"])

In [5]:
df=pd.DataFrame(li,columns=['Tweet','Date','Like','Retweet','Comment','Output'])
df.to_csv('sports.csv')

In [6]:
file=pd.read_csv('sports.csv')
file

,Unnamed: 0,Tweet,Date,Like,Retweet,Comment,Output
0,0,Fans from every corner of the globe uniting in...,2023-02-12 10:46:15+00:00,682,43,19,Sports
1,1,"Football brings us joy, passion, peace and lov...",2023-02-11 13:00:02+00:00,162,25,19,Sports
2,2,"‚ÄúOur aim is to create a more welcoming, inclus...",2023-02-11 11:20:18+00:00,113,21,14,Sports
3,3,The finalists are in for each category for #Th...,2023-02-10 19:57:25+00:00,406,55,73,Sports
4,4,@NormanMaroto üëè,2023-02-10 12:33:47+00:00,1,0,0,Sports
...,...,...,...,...,...,...,...
96,96,"""Football has lost one of its most beautiful a...",2023-01-06 15:57:06+00:00,638,88,4268,Sports
97,97,We are deeply saddened to hear of the passing ...,2023-01-06 10:30:13+00:00,1036,91,99,Sports
98,98,üá®üáª Est√°dio Pel√©\nüá®üá¥ Bello Horizonte Rey Pel√©\n...,2023-01-05 16:01:35+00:00,877,135,53,Sports
99,99,@PLforIndia @BhupsGill_ARef Trailblazer üôå,2023-01-05 10:41:48+00:00,267,5,4,Sports
100,100,@SerieA @OfficialASRoma @Bolognafc1909 ‚ù§Ô∏è,2023-01-05 09:27:20+00:00,19,2,1,Sports